// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptPairingRequest() {
  return window['go']['main']['App']['AcceptPairingRequest']();
}

export function AddGoogleSlidesLink(arg1, arg2) {
  return window['go']['main']['App']['AddGoogleSlidesLink'](arg1, arg2);
}

export function DeletePresentation(arg1) {
  return window['go']['main']['App']['DeletePresentation'](arg1);
}

export function DenyPairingRequest() {
  return window['go']['main']['App']['DenyPairingRequest']();
}

export function EndPresentationSession() {
  return window['go']['main']['App']['EndPresentationSession']();
}

export function ExportPresentationImages(arg1) {
  return window['go']['main']['App']['ExportPresentationImages'](arg1);
}

export function GetLibrary() {
  return window['go']['main']['App']['GetLibrary']();
}

export function GetPresentationBytes(arg1) {
  return window['go']['main']['App']['GetPresentationBytes'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSlideImage(arg1, arg2) {
  return window['go']['main']['App']['GetSlideImage'](arg1, arg2);
}

export function GetSlideImageCompressed(arg1, arg2) {
  return window['go']['main']['App']['GetSlideImageCompressed'](arg1, arg2);
}

export function InitializeStorage(arg1) {
  return window['go']['main']['App']['InitializeStorage'](arg1);
}

export function IsStorageInitialized() {
  return window['go']['main']['App']['IsStorageInitialized']();
}

export function LockStorage() {
  return window['go']['main']['App']['LockStorage']();
}

export function MovePresentationToFolder(arg1, arg2) {
  return window['go']['main']['App']['MovePresentationToFolder'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveSlideImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSlideImage'](arg1, arg2, arg3);
}

export function SelectAndUploadPresentation() {
  return window['go']['main']['App']['SelectAndUploadPresentation']();
}

export function StarPresentation(arg1, arg2) {
  return window['go']['main']['App']['StarPresentation'](arg1, arg2);
}

export function StartPresentationSession(arg1) {
  return window['go']['main']['App']['StartPresentationSession'](arg1);
}

export function UnlockStorage(arg1) {
  return window['go']['main']['App']['UnlockStorage'](arg1);
}

export function UpdateCurrentSlide(arg1) {
  return window['go']['main']['App']['UpdateCurrentSlide'](arg1);
}

export function UploadPresentation(arg1) {
  return window['go']['main']['App']['UploadPresentation'](arg1);
}

export function WriteDebugFile(arg1, arg2) {
  return window['go']['main']['App']['WriteDebugFile'](arg1, arg2);
}
