// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {main} from '../models';

export function AcceptPairingRequest():Promise<void>;

export function AddGoogleSlidesLink(arg1:string,arg2:string):Promise<storage.Presentation>;

export function DeletePresentation(arg1:string):Promise<void>;

export function DenyPairingRequest():Promise<void>;

export function EndPresentationSession():Promise<void>;

export function ExportPresentationImages(arg1:string):Promise<void>;

export function GetLibrary():Promise<Array<storage.Presentation>>;

export function GetPresentationBytes(arg1:string):Promise<Array<number>>;

export function GetSettings():Promise<storage.Settings>;

export function GetSlideImage(arg1:string,arg2:number):Promise<string>;

export function GetSlideImageCompressed(arg1:string,arg2:number):Promise<string>;

export function InitializeStorage(arg1:string):Promise<void>;

export function IsStorageInitialized():Promise<boolean>;

export function LockStorage():Promise<void>;

export function MovePresentationToFolder(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function SaveSlideImage(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SelectAndUploadPresentation():Promise<storage.Presentation>;

export function StarPresentation(arg1:string,arg2:boolean):Promise<void>;

export function StartPresentationSession(arg1:string):Promise<main.SessionInfo>;

export function UnlockStorage(arg1:string):Promise<boolean>;

export function UpdateCurrentSlide(arg1:number):Promise<void>;

export function UploadPresentation(arg1:string):Promise<storage.Presentation>;

export function WriteDebugFile(arg1:string,arg2:string):Promise<void>;
